/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges;

import codechallenges.linkedList.LinkedList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void creates_new_linkedlist() {
      LinkedList newLL = new LinkedList();
      assertEquals(true, newLL instanceof LinkedList, "Should create a new Linked List");
    }

  @Test void add_new_node() {
    LinkedList newLL = new LinkedList();
    newLL.insert(999);
    assertEquals(true, newLL.head.value == 999, "Should create tie in first insert to the head of the linked list");
    assertEquals(999, newLL.head.value, "Should create tie in first insert to the head of the linked list");
  }

  @Test void add_second_new_node() {
    LinkedList newLL = new LinkedList();
    newLL.insert(999);
    newLL.insert(111);
    assertEquals(true, newLL.head.value == 999, "Should add the second node to the head");
    assertEquals(111, newLL.head.next.value, "Should add the second node to the head");
  }

  @Test void includes_value() {
    LinkedList newLL = new LinkedList();
    newLL.insert(999);
    newLL.insert(111);
    newLL.insert(777);
    boolean isTrue = newLL.includes(111);
    boolean isFalse = newLL.includes(8);
    assertEquals(true, isTrue, "Should return true because value is in the linked list");
    assertEquals(false, isFalse, "Should return false because value is NOT in the linked list");
  }

  @Test void return_linkedlist_values() {
    LinkedList newLL = new LinkedList();
    newLL.insert(999);
    newLL.insert(111);
    newLL.insert(777);
    String expectedResult = "{ 999 } -> { 111 } -> { 777 } -> NULL";
    String actualResult = newLL.toString();
    assertEquals(expectedResult, actualResult, "Should return a string with all of the nodes");
  }
}
