/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges;

import codechallenges.linkedList.LinkedList;

public class Library {
    public static void main(String[] args){
    }
}
