/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges;

import codechallenges.linkedList.LinkedList;

public class Library {
    public static void main(String[] args){
      LinkedList newLL = new LinkedList();
//      newLL.insert(999);
////      newLL.insert(111);
////      newLL.insert(777);
////      System.out.println("THIS IS THE HEAD: " + newLL.head.value);
////      System.out.println(newLL.includes(1));
////      System.out.println(newLL.includes(111));
////      System.out.println(newLL.toString());
      System.out.println(newLL.toString());
    }
}
